# Generated by Django 5.2.8 on 2025-12-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roomphoto',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='roomphoto',
            name='url',
        ),
        migrations.AddField(
            model_name='roomphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.room'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.IntegerField(),
        ),
    ]
